BEGIN;
CREATE TABLE product_images
(
    id          BIGINT          NOT NULL    GENERATED BY DEFAULT AS IDENTITY,
    product_id  BIGINT          NOT NULL,
    name        VARCHAR(100)    NOT NULL,

    created_at  TIMESTAMP       NOT NULL    DEFAULT (now() at time zone 'utc'),
    updated_at  TIMESTAMP       NOT NULL    DEFAULT (now() at time zone 'utc'),

    PRIMARY KEY (id),
    CONSTRAINT product_image_product_fk FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT product_images_name_product_id_unique UNIQUE (name, product_id)
);
CREATE UNIQUE INDEX product_images_name_unique ON product_images (name);
COMMIT;
