// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/blackPavlin/shop/internal/database/ent/address"
	"github.com/blackPavlin/shop/internal/database/ent/predicate"
	"github.com/blackPavlin/shop/internal/database/ent/user"
)

// AddressUpdate is the builder for updating Address entities.
type AddressUpdate struct {
	config
	hooks    []Hook
	mutation *AddressMutation
}

// Where appends a list predicates to the AddressUpdate builder.
func (_u *AddressUpdate) Where(ps ...predicate.Address) *AddressUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AddressUpdate) SetUpdatedAt(v time.Time) *AddressUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AddressUpdate) SetUserID(v int64) *AddressUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableUserID(v *int64) *AddressUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCity sets the "city" field.
func (_u *AddressUpdate) SetCity(v string) *AddressUpdate {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableCity(v *string) *AddressUpdate {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// SetCountry sets the "country" field.
func (_u *AddressUpdate) SetCountry(v string) *AddressUpdate {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableCountry(v *string) *AddressUpdate {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// SetFlat sets the "flat" field.
func (_u *AddressUpdate) SetFlat(v int) *AddressUpdate {
	_u.mutation.ResetFlat()
	_u.mutation.SetFlat(v)
	return _u
}

// SetNillableFlat sets the "flat" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableFlat(v *int) *AddressUpdate {
	if v != nil {
		_u.SetFlat(*v)
	}
	return _u
}

// AddFlat adds value to the "flat" field.
func (_u *AddressUpdate) AddFlat(v int) *AddressUpdate {
	_u.mutation.AddFlat(v)
	return _u
}

// ClearFlat clears the value of the "flat" field.
func (_u *AddressUpdate) ClearFlat() *AddressUpdate {
	_u.mutation.ClearFlat()
	return _u
}

// SetHouse sets the "house" field.
func (_u *AddressUpdate) SetHouse(v int) *AddressUpdate {
	_u.mutation.ResetHouse()
	_u.mutation.SetHouse(v)
	return _u
}

// SetNillableHouse sets the "house" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableHouse(v *int) *AddressUpdate {
	if v != nil {
		_u.SetHouse(*v)
	}
	return _u
}

// AddHouse adds value to the "house" field.
func (_u *AddressUpdate) AddHouse(v int) *AddressUpdate {
	_u.mutation.AddHouse(v)
	return _u
}

// SetLetter sets the "letter" field.
func (_u *AddressUpdate) SetLetter(v string) *AddressUpdate {
	_u.mutation.SetLetter(v)
	return _u
}

// SetNillableLetter sets the "letter" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableLetter(v *string) *AddressUpdate {
	if v != nil {
		_u.SetLetter(*v)
	}
	return _u
}

// ClearLetter clears the value of the "letter" field.
func (_u *AddressUpdate) ClearLetter() *AddressUpdate {
	_u.mutation.ClearLetter()
	return _u
}

// SetPostcode sets the "postcode" field.
func (_u *AddressUpdate) SetPostcode(v int) *AddressUpdate {
	_u.mutation.ResetPostcode()
	_u.mutation.SetPostcode(v)
	return _u
}

// SetNillablePostcode sets the "postcode" field if the given value is not nil.
func (_u *AddressUpdate) SetNillablePostcode(v *int) *AddressUpdate {
	if v != nil {
		_u.SetPostcode(*v)
	}
	return _u
}

// AddPostcode adds value to the "postcode" field.
func (_u *AddressUpdate) AddPostcode(v int) *AddressUpdate {
	_u.mutation.AddPostcode(v)
	return _u
}

// SetStreet sets the "street" field.
func (_u *AddressUpdate) SetStreet(v string) *AddressUpdate {
	_u.mutation.SetStreet(v)
	return _u
}

// SetNillableStreet sets the "street" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableStreet(v *string) *AddressUpdate {
	if v != nil {
		_u.SetStreet(*v)
	}
	return _u
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (_u *AddressUpdate) SetUsersID(id int64) *AddressUpdate {
	_u.mutation.SetUsersID(id)
	return _u
}

// SetUsers sets the "users" edge to the User entity.
func (_u *AddressUpdate) SetUsers(v *User) *AddressUpdate {
	return _u.SetUsersID(v.ID)
}

// Mutation returns the AddressMutation object of the builder.
func (_u *AddressUpdate) Mutation() *AddressMutation {
	return _u.mutation
}

// ClearUsers clears the "users" edge to the User entity.
func (_u *AddressUpdate) ClearUsers() *AddressUpdate {
	_u.mutation.ClearUsers()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AddressUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AddressUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AddressUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AddressUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AddressUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := address.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AddressUpdate) check() error {
	if v, ok := _u.mutation.City(); ok {
		if err := address.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Address.city": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Country(); ok {
		if err := address.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "Address.country": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Street(); ok {
		if err := address.StreetValidator(v); err != nil {
			return &ValidationError{Name: "street", err: fmt.Errorf(`ent: validator failed for field "Address.street": %w`, err)}
		}
	}
	if _u.mutation.UsersCleared() && len(_u.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Address.users"`)
	}
	return nil
}

func (_u *AddressUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(address.Table, address.Columns, sqlgraph.NewFieldSpec(address.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(address.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(address.FieldCity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(address.FieldCountry, field.TypeString, value)
	}
	if value, ok := _u.mutation.Flat(); ok {
		_spec.SetField(address.FieldFlat, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFlat(); ok {
		_spec.AddField(address.FieldFlat, field.TypeInt, value)
	}
	if _u.mutation.FlatCleared() {
		_spec.ClearField(address.FieldFlat, field.TypeInt)
	}
	if value, ok := _u.mutation.House(); ok {
		_spec.SetField(address.FieldHouse, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHouse(); ok {
		_spec.AddField(address.FieldHouse, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Letter(); ok {
		_spec.SetField(address.FieldLetter, field.TypeString, value)
	}
	if _u.mutation.LetterCleared() {
		_spec.ClearField(address.FieldLetter, field.TypeString)
	}
	if value, ok := _u.mutation.Postcode(); ok {
		_spec.SetField(address.FieldPostcode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPostcode(); ok {
		_spec.AddField(address.FieldPostcode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Street(); ok {
		_spec.SetField(address.FieldStreet, field.TypeString, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.UsersTable,
			Columns: []string{address.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.UsersTable,
			Columns: []string{address.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{address.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AddressUpdateOne is the builder for updating a single Address entity.
type AddressUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AddressMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AddressUpdateOne) SetUpdatedAt(v time.Time) *AddressUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AddressUpdateOne) SetUserID(v int64) *AddressUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableUserID(v *int64) *AddressUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCity sets the "city" field.
func (_u *AddressUpdateOne) SetCity(v string) *AddressUpdateOne {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableCity(v *string) *AddressUpdateOne {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// SetCountry sets the "country" field.
func (_u *AddressUpdateOne) SetCountry(v string) *AddressUpdateOne {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableCountry(v *string) *AddressUpdateOne {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// SetFlat sets the "flat" field.
func (_u *AddressUpdateOne) SetFlat(v int) *AddressUpdateOne {
	_u.mutation.ResetFlat()
	_u.mutation.SetFlat(v)
	return _u
}

// SetNillableFlat sets the "flat" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableFlat(v *int) *AddressUpdateOne {
	if v != nil {
		_u.SetFlat(*v)
	}
	return _u
}

// AddFlat adds value to the "flat" field.
func (_u *AddressUpdateOne) AddFlat(v int) *AddressUpdateOne {
	_u.mutation.AddFlat(v)
	return _u
}

// ClearFlat clears the value of the "flat" field.
func (_u *AddressUpdateOne) ClearFlat() *AddressUpdateOne {
	_u.mutation.ClearFlat()
	return _u
}

// SetHouse sets the "house" field.
func (_u *AddressUpdateOne) SetHouse(v int) *AddressUpdateOne {
	_u.mutation.ResetHouse()
	_u.mutation.SetHouse(v)
	return _u
}

// SetNillableHouse sets the "house" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableHouse(v *int) *AddressUpdateOne {
	if v != nil {
		_u.SetHouse(*v)
	}
	return _u
}

// AddHouse adds value to the "house" field.
func (_u *AddressUpdateOne) AddHouse(v int) *AddressUpdateOne {
	_u.mutation.AddHouse(v)
	return _u
}

// SetLetter sets the "letter" field.
func (_u *AddressUpdateOne) SetLetter(v string) *AddressUpdateOne {
	_u.mutation.SetLetter(v)
	return _u
}

// SetNillableLetter sets the "letter" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableLetter(v *string) *AddressUpdateOne {
	if v != nil {
		_u.SetLetter(*v)
	}
	return _u
}

// ClearLetter clears the value of the "letter" field.
func (_u *AddressUpdateOne) ClearLetter() *AddressUpdateOne {
	_u.mutation.ClearLetter()
	return _u
}

// SetPostcode sets the "postcode" field.
func (_u *AddressUpdateOne) SetPostcode(v int) *AddressUpdateOne {
	_u.mutation.ResetPostcode()
	_u.mutation.SetPostcode(v)
	return _u
}

// SetNillablePostcode sets the "postcode" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillablePostcode(v *int) *AddressUpdateOne {
	if v != nil {
		_u.SetPostcode(*v)
	}
	return _u
}

// AddPostcode adds value to the "postcode" field.
func (_u *AddressUpdateOne) AddPostcode(v int) *AddressUpdateOne {
	_u.mutation.AddPostcode(v)
	return _u
}

// SetStreet sets the "street" field.
func (_u *AddressUpdateOne) SetStreet(v string) *AddressUpdateOne {
	_u.mutation.SetStreet(v)
	return _u
}

// SetNillableStreet sets the "street" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableStreet(v *string) *AddressUpdateOne {
	if v != nil {
		_u.SetStreet(*v)
	}
	return _u
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (_u *AddressUpdateOne) SetUsersID(id int64) *AddressUpdateOne {
	_u.mutation.SetUsersID(id)
	return _u
}

// SetUsers sets the "users" edge to the User entity.
func (_u *AddressUpdateOne) SetUsers(v *User) *AddressUpdateOne {
	return _u.SetUsersID(v.ID)
}

// Mutation returns the AddressMutation object of the builder.
func (_u *AddressUpdateOne) Mutation() *AddressMutation {
	return _u.mutation
}

// ClearUsers clears the "users" edge to the User entity.
func (_u *AddressUpdateOne) ClearUsers() *AddressUpdateOne {
	_u.mutation.ClearUsers()
	return _u
}

// Where appends a list predicates to the AddressUpdate builder.
func (_u *AddressUpdateOne) Where(ps ...predicate.Address) *AddressUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AddressUpdateOne) Select(field string, fields ...string) *AddressUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Address entity.
func (_u *AddressUpdateOne) Save(ctx context.Context) (*Address, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AddressUpdateOne) SaveX(ctx context.Context) *Address {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AddressUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AddressUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AddressUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := address.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AddressUpdateOne) check() error {
	if v, ok := _u.mutation.City(); ok {
		if err := address.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Address.city": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Country(); ok {
		if err := address.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "Address.country": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Street(); ok {
		if err := address.StreetValidator(v); err != nil {
			return &ValidationError{Name: "street", err: fmt.Errorf(`ent: validator failed for field "Address.street": %w`, err)}
		}
	}
	if _u.mutation.UsersCleared() && len(_u.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Address.users"`)
	}
	return nil
}

func (_u *AddressUpdateOne) sqlSave(ctx context.Context) (_node *Address, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(address.Table, address.Columns, sqlgraph.NewFieldSpec(address.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Address.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, address.FieldID)
		for _, f := range fields {
			if !address.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != address.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(address.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(address.FieldCity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(address.FieldCountry, field.TypeString, value)
	}
	if value, ok := _u.mutation.Flat(); ok {
		_spec.SetField(address.FieldFlat, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFlat(); ok {
		_spec.AddField(address.FieldFlat, field.TypeInt, value)
	}
	if _u.mutation.FlatCleared() {
		_spec.ClearField(address.FieldFlat, field.TypeInt)
	}
	if value, ok := _u.mutation.House(); ok {
		_spec.SetField(address.FieldHouse, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHouse(); ok {
		_spec.AddField(address.FieldHouse, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Letter(); ok {
		_spec.SetField(address.FieldLetter, field.TypeString, value)
	}
	if _u.mutation.LetterCleared() {
		_spec.ClearField(address.FieldLetter, field.TypeString)
	}
	if value, ok := _u.mutation.Postcode(); ok {
		_spec.SetField(address.FieldPostcode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPostcode(); ok {
		_spec.AddField(address.FieldPostcode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Street(); ok {
		_spec.SetField(address.FieldStreet, field.TypeString, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.UsersTable,
			Columns: []string{address.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.UsersTable,
			Columns: []string{address.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Address{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{address.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
