// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/blackPavlin/shop/internal/database/ent/cart"
	"github.com/blackPavlin/shop/internal/database/ent/predicate"
	"github.com/blackPavlin/shop/internal/database/ent/product"
	"github.com/blackPavlin/shop/internal/database/ent/user"
)

// CartUpdate is the builder for updating Cart entities.
type CartUpdate struct {
	config
	hooks    []Hook
	mutation *CartMutation
}

// Where appends a list predicates to the CartUpdate builder.
func (_u *CartUpdate) Where(ps ...predicate.Cart) *CartUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CartUpdate) SetUpdatedAt(v time.Time) *CartUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CartUpdate) SetUserID(v int64) *CartUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CartUpdate) SetNillableUserID(v *int64) *CartUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *CartUpdate) SetProductID(v int64) *CartUpdate {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *CartUpdate) SetNillableProductID(v *int64) *CartUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *CartUpdate) SetAmount(v int64) *CartUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *CartUpdate) SetNillableAmount(v *int64) *CartUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *CartUpdate) AddAmount(v int64) *CartUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (_u *CartUpdate) SetUsersID(id int64) *CartUpdate {
	_u.mutation.SetUsersID(id)
	return _u
}

// SetUsers sets the "users" edge to the User entity.
func (_u *CartUpdate) SetUsers(v *User) *CartUpdate {
	return _u.SetUsersID(v.ID)
}

// SetProductsID sets the "products" edge to the Product entity by ID.
func (_u *CartUpdate) SetProductsID(id int64) *CartUpdate {
	_u.mutation.SetProductsID(id)
	return _u
}

// SetProducts sets the "products" edge to the Product entity.
func (_u *CartUpdate) SetProducts(v *Product) *CartUpdate {
	return _u.SetProductsID(v.ID)
}

// Mutation returns the CartMutation object of the builder.
func (_u *CartUpdate) Mutation() *CartMutation {
	return _u.mutation
}

// ClearUsers clears the "users" edge to the User entity.
func (_u *CartUpdate) ClearUsers() *CartUpdate {
	_u.mutation.ClearUsers()
	return _u
}

// ClearProducts clears the "products" edge to the Product entity.
func (_u *CartUpdate) ClearProducts() *CartUpdate {
	_u.mutation.ClearProducts()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CartUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CartUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CartUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CartUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CartUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := cart.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CartUpdate) check() error {
	if v, ok := _u.mutation.Amount(); ok {
		if err := cart.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "Cart.amount": %w`, err)}
		}
	}
	if _u.mutation.UsersCleared() && len(_u.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Cart.users"`)
	}
	if _u.mutation.ProductsCleared() && len(_u.mutation.ProductsIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Cart.products"`)
	}
	return nil
}

func (_u *CartUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cart.Table, cart.Columns, sqlgraph.NewFieldSpec(cart.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cart.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(cart.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(cart.FieldAmount, field.TypeInt64, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cart.UsersTable,
			Columns: []string{cart.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cart.UsersTable,
			Columns: []string{cart.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cart.ProductsTable,
			Columns: []string{cart.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cart.ProductsTable,
			Columns: []string{cart.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cart.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CartUpdateOne is the builder for updating a single Cart entity.
type CartUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CartMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CartUpdateOne) SetUpdatedAt(v time.Time) *CartUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CartUpdateOne) SetUserID(v int64) *CartUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CartUpdateOne) SetNillableUserID(v *int64) *CartUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *CartUpdateOne) SetProductID(v int64) *CartUpdateOne {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *CartUpdateOne) SetNillableProductID(v *int64) *CartUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *CartUpdateOne) SetAmount(v int64) *CartUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *CartUpdateOne) SetNillableAmount(v *int64) *CartUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *CartUpdateOne) AddAmount(v int64) *CartUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (_u *CartUpdateOne) SetUsersID(id int64) *CartUpdateOne {
	_u.mutation.SetUsersID(id)
	return _u
}

// SetUsers sets the "users" edge to the User entity.
func (_u *CartUpdateOne) SetUsers(v *User) *CartUpdateOne {
	return _u.SetUsersID(v.ID)
}

// SetProductsID sets the "products" edge to the Product entity by ID.
func (_u *CartUpdateOne) SetProductsID(id int64) *CartUpdateOne {
	_u.mutation.SetProductsID(id)
	return _u
}

// SetProducts sets the "products" edge to the Product entity.
func (_u *CartUpdateOne) SetProducts(v *Product) *CartUpdateOne {
	return _u.SetProductsID(v.ID)
}

// Mutation returns the CartMutation object of the builder.
func (_u *CartUpdateOne) Mutation() *CartMutation {
	return _u.mutation
}

// ClearUsers clears the "users" edge to the User entity.
func (_u *CartUpdateOne) ClearUsers() *CartUpdateOne {
	_u.mutation.ClearUsers()
	return _u
}

// ClearProducts clears the "products" edge to the Product entity.
func (_u *CartUpdateOne) ClearProducts() *CartUpdateOne {
	_u.mutation.ClearProducts()
	return _u
}

// Where appends a list predicates to the CartUpdate builder.
func (_u *CartUpdateOne) Where(ps ...predicate.Cart) *CartUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CartUpdateOne) Select(field string, fields ...string) *CartUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Cart entity.
func (_u *CartUpdateOne) Save(ctx context.Context) (*Cart, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CartUpdateOne) SaveX(ctx context.Context) *Cart {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CartUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CartUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CartUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := cart.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CartUpdateOne) check() error {
	if v, ok := _u.mutation.Amount(); ok {
		if err := cart.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "Cart.amount": %w`, err)}
		}
	}
	if _u.mutation.UsersCleared() && len(_u.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Cart.users"`)
	}
	if _u.mutation.ProductsCleared() && len(_u.mutation.ProductsIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Cart.products"`)
	}
	return nil
}

func (_u *CartUpdateOne) sqlSave(ctx context.Context) (_node *Cart, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cart.Table, cart.Columns, sqlgraph.NewFieldSpec(cart.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Cart.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cart.FieldID)
		for _, f := range fields {
			if !cart.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cart.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cart.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(cart.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(cart.FieldAmount, field.TypeInt64, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cart.UsersTable,
			Columns: []string{cart.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cart.UsersTable,
			Columns: []string{cart.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cart.ProductsTable,
			Columns: []string{cart.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cart.ProductsTable,
			Columns: []string{cart.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Cart{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cart.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
