// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/blackPavlin/shop/internal/database/ent/predicate"
	"github.com/blackPavlin/shop/internal/database/ent/product"
	"github.com/blackPavlin/shop/internal/database/ent/productimage"
)

// ProductImageUpdate is the builder for updating ProductImage entities.
type ProductImageUpdate struct {
	config
	hooks    []Hook
	mutation *ProductImageMutation
}

// Where appends a list predicates to the ProductImageUpdate builder.
func (_u *ProductImageUpdate) Where(ps ...predicate.ProductImage) *ProductImageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProductImageUpdate) SetUpdatedAt(v time.Time) *ProductImageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *ProductImageUpdate) SetProductID(v int64) *ProductImageUpdate {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *ProductImageUpdate) SetNillableProductID(v *int64) *ProductImageUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ProductImageUpdate) SetName(v string) *ProductImageUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProductImageUpdate) SetNillableName(v *string) *ProductImageUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProductsID sets the "products" edge to the Product entity by ID.
func (_u *ProductImageUpdate) SetProductsID(id int64) *ProductImageUpdate {
	_u.mutation.SetProductsID(id)
	return _u
}

// SetProducts sets the "products" edge to the Product entity.
func (_u *ProductImageUpdate) SetProducts(v *Product) *ProductImageUpdate {
	return _u.SetProductsID(v.ID)
}

// Mutation returns the ProductImageMutation object of the builder.
func (_u *ProductImageUpdate) Mutation() *ProductImageMutation {
	return _u.mutation
}

// ClearProducts clears the "products" edge to the Product entity.
func (_u *ProductImageUpdate) ClearProducts() *ProductImageUpdate {
	_u.mutation.ClearProducts()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProductImageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductImageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProductImageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductImageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProductImageUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := productimage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProductImageUpdate) check() error {
	if _u.mutation.ProductsCleared() && len(_u.mutation.ProductsIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProductImage.products"`)
	}
	return nil
}

func (_u *ProductImageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(productimage.Table, productimage.Columns, sqlgraph.NewFieldSpec(productimage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(productimage.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(productimage.FieldName, field.TypeString, value)
	}
	if _u.mutation.ProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   productimage.ProductsTable,
			Columns: []string{productimage.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   productimage.ProductsTable,
			Columns: []string{productimage.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{productimage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProductImageUpdateOne is the builder for updating a single ProductImage entity.
type ProductImageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProductImageMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProductImageUpdateOne) SetUpdatedAt(v time.Time) *ProductImageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *ProductImageUpdateOne) SetProductID(v int64) *ProductImageUpdateOne {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *ProductImageUpdateOne) SetNillableProductID(v *int64) *ProductImageUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ProductImageUpdateOne) SetName(v string) *ProductImageUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProductImageUpdateOne) SetNillableName(v *string) *ProductImageUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProductsID sets the "products" edge to the Product entity by ID.
func (_u *ProductImageUpdateOne) SetProductsID(id int64) *ProductImageUpdateOne {
	_u.mutation.SetProductsID(id)
	return _u
}

// SetProducts sets the "products" edge to the Product entity.
func (_u *ProductImageUpdateOne) SetProducts(v *Product) *ProductImageUpdateOne {
	return _u.SetProductsID(v.ID)
}

// Mutation returns the ProductImageMutation object of the builder.
func (_u *ProductImageUpdateOne) Mutation() *ProductImageMutation {
	return _u.mutation
}

// ClearProducts clears the "products" edge to the Product entity.
func (_u *ProductImageUpdateOne) ClearProducts() *ProductImageUpdateOne {
	_u.mutation.ClearProducts()
	return _u
}

// Where appends a list predicates to the ProductImageUpdate builder.
func (_u *ProductImageUpdateOne) Where(ps ...predicate.ProductImage) *ProductImageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProductImageUpdateOne) Select(field string, fields ...string) *ProductImageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProductImage entity.
func (_u *ProductImageUpdateOne) Save(ctx context.Context) (*ProductImage, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductImageUpdateOne) SaveX(ctx context.Context) *ProductImage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProductImageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductImageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProductImageUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := productimage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProductImageUpdateOne) check() error {
	if _u.mutation.ProductsCleared() && len(_u.mutation.ProductsIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProductImage.products"`)
	}
	return nil
}

func (_u *ProductImageUpdateOne) sqlSave(ctx context.Context) (_node *ProductImage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(productimage.Table, productimage.Columns, sqlgraph.NewFieldSpec(productimage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProductImage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, productimage.FieldID)
		for _, f := range fields {
			if !productimage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != productimage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(productimage.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(productimage.FieldName, field.TypeString, value)
	}
	if _u.mutation.ProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   productimage.ProductsTable,
			Columns: []string{productimage.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   productimage.ProductsTable,
			Columns: []string{productimage.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProductImage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{productimage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
